services:
  php:
    build:
      context: ./cocohairsignature.com
    container_name: php-html
    restart: unless-stopped
    networks:
      - shared-global-network
    env_file:
      - _env/dev/stripe.env
      - _env/dev/smtp.env
      - _env/dev/admin.env
      - _env/dev/db.env
    volumes:
      - ./cocohairsignature.com:/var/www/html

networks:
  shared-global-network:
    external: true