services:
  coco_php:
    build:
      context: ./cocohairsignature.com
    container_name: coco_php
    restart: unless-stopped 
    networks:
      - shared-global-network
    env_file:
      - _env/${STAGE}/stripe.env
      - _env/${STAGE}/smtp.env
      - _env/${STAGE}/admin.env
      - _env/${STAGE}/db.env


networks:
  shared-global-network:
    external: true