services:
  php:
    build:
      context: ./cocohairsignature.com
    container_name: cocohairsignature.com-php
    ports:
      - "1008:80"
    volumes:
      - ./cocohairsignature.com:/var/www/html
      #- ./httplog.log:/var/log/apache2/access.log
      #- ./httperror.log:/var/log/apache2/error.log
    restart: unless-stopped
    networks:
      - shared-global-network
    env_file:
      - _env/dev/stripe.env
      - _env/dev/smtp.env
      - _env/dev/admin.env
      - _env/dev/db.env

networks:
  shared-global-network:
    external: true